/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarCorreoRouteImport } from './routes/verificar-correo'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendedoresSlugRouteImport } from './routes/vendedores.$slug'
import { Route as OfertaSlugRouteImport } from './routes/oferta.$slug'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'

const VerificarCorreoRoute = VerificarCorreoRouteImport.update({
  id: '/verificar-correo',
  path: '/verificar-correo',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresSlugRoute = VendedoresSlugRouteImport.update({
  id: '/vendedores/$slug',
  path: '/vendedores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaSlugRoute = OfertaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OfertaRoute,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/ingresar': typeof IngresarRoute
  '/oferta': typeof OfertaRouteWithChildren
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/soporte': typeof SoporteRoute
  '/verificar-correo': typeof VerificarCorreoRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/oferta/$slug': typeof OfertaSlugRoute
  '/vendedores/$slug': typeof VendedoresSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/ingresar': typeof IngresarRoute
  '/oferta': typeof OfertaRouteWithChildren
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/soporte': typeof SoporteRoute
  '/verificar-correo': typeof VerificarCorreoRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/oferta/$slug': typeof OfertaSlugRoute
  '/vendedores/$slug': typeof VendedoresSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/ingresar': typeof IngresarRoute
  '/oferta': typeof OfertaRouteWithChildren
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/soporte': typeof SoporteRoute
  '/verificar-correo': typeof VerificarCorreoRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/oferta/$slug': typeof OfertaSlugRoute
  '/vendedores/$slug': typeof VendedoresSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/categorias'
    | '/contacto'
    | '/faq'
    | '/ingresar'
    | '/oferta'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/sobre-nosotros'
    | '/soporte'
    | '/verificar-correo'
    | '/categorias/$slug'
    | '/oferta/$slug'
    | '/vendedores/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/categorias'
    | '/contacto'
    | '/faq'
    | '/ingresar'
    | '/oferta'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/sobre-nosotros'
    | '/soporte'
    | '/verificar-correo'
    | '/categorias/$slug'
    | '/oferta/$slug'
    | '/vendedores/$slug'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/categorias'
    | '/contacto'
    | '/faq'
    | '/ingresar'
    | '/oferta'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/sobre-nosotros'
    | '/soporte'
    | '/verificar-correo'
    | '/categorias/$slug'
    | '/oferta/$slug'
    | '/vendedores/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  FaqRoute: typeof FaqRoute
  IngresarRoute: typeof IngresarRoute
  OfertaRoute: typeof OfertaRouteWithChildren
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  RestablecerRoute: typeof RestablecerRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  SoporteRoute: typeof SoporteRoute
  VerificarCorreoRoute: typeof VerificarCorreoRoute
  VendedoresSlugRoute: typeof VendedoresSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar-correo': {
      id: '/verificar-correo'
      path: '/verificar-correo'
      fullPath: '/verificar-correo'
      preLoaderRoute: typeof VerificarCorreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores/$slug': {
      id: '/vendedores/$slug'
      path: '/vendedores/$slug'
      fullPath: '/vendedores/$slug'
      preLoaderRoute: typeof VendedoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta/$slug': {
      id: '/oferta/$slug'
      path: '/$slug'
      fullPath: '/oferta/$slug'
      preLoaderRoute: typeof OfertaSlugRouteImport
      parentRoute: typeof OfertaRoute
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof CategoriasRoute
    }
  }
}

interface CategoriasRouteChildren {
  CategoriasSlugRoute: typeof CategoriasSlugRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasSlugRoute: CategoriasSlugRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

interface OfertaRouteChildren {
  OfertaSlugRoute: typeof OfertaSlugRoute
}

const OfertaRouteChildren: OfertaRouteChildren = {
  OfertaSlugRoute: OfertaSlugRoute,
}

const OfertaRouteWithChildren =
  OfertaRoute._addFileChildren(OfertaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  ContactoRoute: ContactoRoute,
  FaqRoute: FaqRoute,
  IngresarRoute: IngresarRoute,
  OfertaRoute: OfertaRouteWithChildren,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  RestablecerRoute: RestablecerRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  SoporteRoute: SoporteRoute,
  VerificarCorreoRoute: VerificarCorreoRoute,
  VendedoresSlugRoute: VendedoresSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
