/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarCorreoRouteImport } from './routes/verificar-correo'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as MantenimientoRouteImport } from './routes/mantenimiento'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CompradorRouteImport } from './routes/comprador'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as VendedoresSlugRouteImport } from './routes/vendedores.$slug'
import { Route as PanelPublicarRouteImport } from './routes/panel.publicar'
import { Route as PanelPerfilRouteImport } from './routes/panel.perfil'
import { Route as PanelOfertaRouteImport } from './routes/panel.oferta'
import { Route as PanelNotificacionesRouteImport } from './routes/panel.notificaciones'
import { Route as PanelLeadsRouteImport } from './routes/panel.leads'
import { Route as PanelFacturacionRouteImport } from './routes/panel.facturacion'
import { Route as PanelAjustesRouteImport } from './routes/panel.ajustes'
import { Route as OfertaSlugRouteImport } from './routes/oferta.$slug'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'

const VerificarCorreoRoute = VerificarCorreoRouteImport.update({
  id: '/verificar-correo',
  path: '/verificar-correo',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const MantenimientoRoute = MantenimientoRouteImport.update({
  id: '/mantenimiento',
  path: '/mantenimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CompradorRoute = CompradorRouteImport.update({
  id: '/comprador',
  path: '/comprador',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const VendedoresSlugRoute = VendedoresSlugRouteImport.update({
  id: '/vendedores/$slug',
  path: '/vendedores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelPublicarRoute = PanelPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPerfilRoute = PanelPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PanelRoute,
} as any)
const PanelOfertaRoute = PanelOfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => PanelRoute,
} as any)
const PanelNotificacionesRoute = PanelNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => PanelRoute,
} as any)
const PanelLeadsRoute = PanelLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PanelRoute,
} as any)
const PanelFacturacionRoute = PanelFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAjustesRoute = PanelAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => PanelRoute,
} as any)
const OfertaSlugRoute = OfertaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OfertaRoute,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/comprador': typeof CompradorRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/gracias': typeof GraciasRoute
  '/ingresar': typeof IngresarRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/oferta': typeof OfertaRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/panel': typeof PanelRouteWithChildren
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/soporte': typeof SoporteRoute
  '/terminos': typeof TerminosRoute
  '/verificar-correo': typeof VerificarCorreoRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/oferta/$slug': typeof OfertaSlugRoute
  '/panel/ajustes': typeof PanelAjustesRoute
  '/panel/facturacion': typeof PanelFacturacionRoute
  '/panel/leads': typeof PanelLeadsRoute
  '/panel/notificaciones': typeof PanelNotificacionesRoute
  '/panel/oferta': typeof PanelOfertaRoute
  '/panel/perfil': typeof PanelPerfilRoute
  '/panel/publicar': typeof PanelPublicarRoute
  '/vendedores/$slug': typeof VendedoresSlugRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/comprador': typeof CompradorRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/gracias': typeof GraciasRoute
  '/ingresar': typeof IngresarRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/oferta': typeof OfertaRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/soporte': typeof SoporteRoute
  '/terminos': typeof TerminosRoute
  '/verificar-correo': typeof VerificarCorreoRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/oferta/$slug': typeof OfertaSlugRoute
  '/panel/ajustes': typeof PanelAjustesRoute
  '/panel/facturacion': typeof PanelFacturacionRoute
  '/panel/leads': typeof PanelLeadsRoute
  '/panel/notificaciones': typeof PanelNotificacionesRoute
  '/panel/oferta': typeof PanelOfertaRoute
  '/panel/perfil': typeof PanelPerfilRoute
  '/panel/publicar': typeof PanelPublicarRoute
  '/vendedores/$slug': typeof VendedoresSlugRoute
  '/panel': typeof PanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/comprador': typeof CompradorRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/gracias': typeof GraciasRoute
  '/ingresar': typeof IngresarRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/oferta': typeof OfertaRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/panel': typeof PanelRouteWithChildren
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/soporte': typeof SoporteRoute
  '/terminos': typeof TerminosRoute
  '/verificar-correo': typeof VerificarCorreoRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/oferta/$slug': typeof OfertaSlugRoute
  '/panel/ajustes': typeof PanelAjustesRoute
  '/panel/facturacion': typeof PanelFacturacionRoute
  '/panel/leads': typeof PanelLeadsRoute
  '/panel/notificaciones': typeof PanelNotificacionesRoute
  '/panel/oferta': typeof PanelOfertaRoute
  '/panel/perfil': typeof PanelPerfilRoute
  '/panel/publicar': typeof PanelPublicarRoute
  '/vendedores/$slug': typeof VendedoresSlugRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buscar'
    | '/categorias'
    | '/checkout'
    | '/comprador'
    | '/contacto'
    | '/cookies'
    | '/faq'
    | '/gracias'
    | '/ingresar'
    | '/mantenimiento'
    | '/oferta'
    | '/onboarding'
    | '/panel'
    | '/precios'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/sobre-nosotros'
    | '/soporte'
    | '/terminos'
    | '/verificar-correo'
    | '/categorias/$slug'
    | '/oferta/$slug'
    | '/panel/ajustes'
    | '/panel/facturacion'
    | '/panel/leads'
    | '/panel/notificaciones'
    | '/panel/oferta'
    | '/panel/perfil'
    | '/panel/publicar'
    | '/vendedores/$slug'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/buscar'
    | '/categorias'
    | '/checkout'
    | '/comprador'
    | '/contacto'
    | '/cookies'
    | '/faq'
    | '/gracias'
    | '/ingresar'
    | '/mantenimiento'
    | '/oferta'
    | '/onboarding'
    | '/precios'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/sobre-nosotros'
    | '/soporte'
    | '/terminos'
    | '/verificar-correo'
    | '/categorias/$slug'
    | '/oferta/$slug'
    | '/panel/ajustes'
    | '/panel/facturacion'
    | '/panel/leads'
    | '/panel/notificaciones'
    | '/panel/oferta'
    | '/panel/perfil'
    | '/panel/publicar'
    | '/vendedores/$slug'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buscar'
    | '/categorias'
    | '/checkout'
    | '/comprador'
    | '/contacto'
    | '/cookies'
    | '/faq'
    | '/gracias'
    | '/ingresar'
    | '/mantenimiento'
    | '/oferta'
    | '/onboarding'
    | '/panel'
    | '/precios'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/sobre-nosotros'
    | '/soporte'
    | '/terminos'
    | '/verificar-correo'
    | '/categorias/$slug'
    | '/oferta/$slug'
    | '/panel/ajustes'
    | '/panel/facturacion'
    | '/panel/leads'
    | '/panel/notificaciones'
    | '/panel/oferta'
    | '/panel/perfil'
    | '/panel/publicar'
    | '/vendedores/$slug'
    | '/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuscarRoute: typeof BuscarRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CompradorRoute: typeof CompradorRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  GraciasRoute: typeof GraciasRoute
  IngresarRoute: typeof IngresarRoute
  MantenimientoRoute: typeof MantenimientoRoute
  OfertaRoute: typeof OfertaRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PanelRoute: typeof PanelRouteWithChildren
  PreciosRoute: typeof PreciosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  RestablecerRoute: typeof RestablecerRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  SoporteRoute: typeof SoporteRoute
  TerminosRoute: typeof TerminosRoute
  VerificarCorreoRoute: typeof VerificarCorreoRoute
  VendedoresSlugRoute: typeof VendedoresSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar-correo': {
      id: '/verificar-correo'
      path: '/verificar-correo'
      fullPath: '/verificar-correo'
      preLoaderRoute: typeof VerificarCorreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantenimiento': {
      id: '/mantenimiento'
      path: '/mantenimiento'
      fullPath: '/mantenimiento'
      preLoaderRoute: typeof MantenimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprador': {
      id: '/comprador'
      path: '/comprador'
      fullPath: '/comprador'
      preLoaderRoute: typeof CompradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/vendedores/$slug': {
      id: '/vendedores/$slug'
      path: '/vendedores/$slug'
      fullPath: '/vendedores/$slug'
      preLoaderRoute: typeof VendedoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/publicar': {
      id: '/panel/publicar'
      path: '/publicar'
      fullPath: '/panel/publicar'
      preLoaderRoute: typeof PanelPublicarRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/perfil': {
      id: '/panel/perfil'
      path: '/perfil'
      fullPath: '/panel/perfil'
      preLoaderRoute: typeof PanelPerfilRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/oferta': {
      id: '/panel/oferta'
      path: '/oferta'
      fullPath: '/panel/oferta'
      preLoaderRoute: typeof PanelOfertaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/notificaciones': {
      id: '/panel/notificaciones'
      path: '/notificaciones'
      fullPath: '/panel/notificaciones'
      preLoaderRoute: typeof PanelNotificacionesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/leads': {
      id: '/panel/leads'
      path: '/leads'
      fullPath: '/panel/leads'
      preLoaderRoute: typeof PanelLeadsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/facturacion': {
      id: '/panel/facturacion'
      path: '/facturacion'
      fullPath: '/panel/facturacion'
      preLoaderRoute: typeof PanelFacturacionRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/ajustes': {
      id: '/panel/ajustes'
      path: '/ajustes'
      fullPath: '/panel/ajustes'
      preLoaderRoute: typeof PanelAjustesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/oferta/$slug': {
      id: '/oferta/$slug'
      path: '/$slug'
      fullPath: '/oferta/$slug'
      preLoaderRoute: typeof OfertaSlugRouteImport
      parentRoute: typeof OfertaRoute
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof CategoriasRoute
    }
  }
}

interface CategoriasRouteChildren {
  CategoriasSlugRoute: typeof CategoriasSlugRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasSlugRoute: CategoriasSlugRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

interface OfertaRouteChildren {
  OfertaSlugRoute: typeof OfertaSlugRoute
}

const OfertaRouteChildren: OfertaRouteChildren = {
  OfertaSlugRoute: OfertaSlugRoute,
}

const OfertaRouteWithChildren =
  OfertaRoute._addFileChildren(OfertaRouteChildren)

interface PanelRouteChildren {
  PanelAjustesRoute: typeof PanelAjustesRoute
  PanelFacturacionRoute: typeof PanelFacturacionRoute
  PanelLeadsRoute: typeof PanelLeadsRoute
  PanelNotificacionesRoute: typeof PanelNotificacionesRoute
  PanelOfertaRoute: typeof PanelOfertaRoute
  PanelPerfilRoute: typeof PanelPerfilRoute
  PanelPublicarRoute: typeof PanelPublicarRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAjustesRoute: PanelAjustesRoute,
  PanelFacturacionRoute: PanelFacturacionRoute,
  PanelLeadsRoute: PanelLeadsRoute,
  PanelNotificacionesRoute: PanelNotificacionesRoute,
  PanelOfertaRoute: PanelOfertaRoute,
  PanelPerfilRoute: PanelPerfilRoute,
  PanelPublicarRoute: PanelPublicarRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuscarRoute: BuscarRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CompradorRoute: CompradorRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  GraciasRoute: GraciasRoute,
  IngresarRoute: IngresarRoute,
  MantenimientoRoute: MantenimientoRoute,
  OfertaRoute: OfertaRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PanelRoute: PanelRouteWithChildren,
  PreciosRoute: PreciosRoute,
  PrivacidadRoute: PrivacidadRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  RestablecerRoute: RestablecerRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  SoporteRoute: SoporteRoute,
  TerminosRoute: TerminosRoute,
  VerificarCorreoRoute: VerificarCorreoRoute,
  VendedoresSlugRoute: VendedoresSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
